//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCCME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patrimonio
    {
        public int PatCodigo { get; set; }
        public string PatNome { get; set; }
        public string PatHistoria { get; set; }
        public string PatEndereco { get; set; }
        public string PatFoto1 { get; set; }
        public string PatFoto2 { get; set; }
        public string PatFoto3 { get; set; }
        public string PatFoto4 { get; set; }
        public string PatFoto5 { get; set; }
        public int PatAcessos { get; set; }
        public string PatHorario { get; set; }
    }
}
